---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: grpc-guide
  name: grpc-config
data:
  # refers to: certs/server.pem
  grpc-service.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIC9zCCAd8CCQCQeQd01F+8hDANBgkqhkiG9w0BAQUFADBCMQswCQYDVQQGEwJV
    UzETMBEGA1UECAwKc29tZS1zdGF0ZTENMAsGA1UECgwEdGVzdDEPMA0GA1UEAwwG
    dGVzdGNhMB4XDTIyMTIwNjIwMjIyOFoXDTMyMTIwMzIwMjIyOFowOTE3MDUGA1UE
    AwwuKi5hcHBzLnNoYXJlZC00MTAub3BlbnNoaWZ0LnJlZGhhdHdvcmtzaG9wcy5p
    bzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMFdDXUnDvORpkjYopH6
    1665LA/9Ajcl95WhjZ59uo7WGns/+sQ06lZaq9El9EQaD21px71FV525x8K9hzJC
    lohPYZdD7+huGMXDI3OShDP4M5hoOmDdd2eI6LzsphhGVm8lRj/sLKS58XwFBgBs
    X9v+P8/Ij6qTXlYsrgwA7NRqSnx+r2EEmZ0OHlL0P6I20EyWE5+TxMPndUrhBKki
    1ctvI0zGXPUS7zU87rEo+F389h6bNBDSk/o2npI1jLQvXMfEfxd0ZCaFYIDdRMh1
    c0DLXbeR+Fehps2EEKo/pD1nV/Zty+XtiAOYDK3CIiRmi98dacpy3oNLei2YvMAF
    HUECAwEAATANBgkqhkiG9w0BAQUFAAOCAQEAn6NKuCdMmN62ZYi4vLvr2GtKJoHs
    nYneeH4NM1geYhKXw3eNZqE/JJ4uhiXonwg8bwSO5gAdvdYXiCOSlnH0JLFq8uQV
    yZV/KaV14IN5NAEtwHSM4iLhKxrBpczJBCKc23xwKe08ZknZNf8MXQaEwzs1wSF2
    49WEVqxrs6Bw4OqpKX90VP3ChCmWmEjoTEp86y2P2UbZqr4f363KrlMtJ8z+4emo
    SeMcogSwyB/KimHFjyDpr3y0tqK/2LvfgPaoX2l4gZLDp0TEI9QaPDmd9r6fOigq
    VJLa3PEv1M+5t4I35uV8GNWDNpJctNf5wRaT6vpsOtUJAYE2F4aOt8Ksrg==
    -----END CERTIFICATE-----

  # refers to: certs/server.key
  grpc-service.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDBXQ11Jw7zkaZI
    2KKR+teuuSwP/QI3JfeVoY2efbqO1hp7P/rENOpWWqvRJfREGg9tace9RVeducfC
    vYcyQpaIT2GXQ+/obhjFwyNzkoQz+DOYaDpg3XdniOi87KYYRlZvJUY/7CykufF8
    BQYAbF/b/j/PyI+qk15WLK4MAOzUakp8fq9hBJmdDh5S9D+iNtBMlhOfk8TD53VK
    4QSpItXLbyNMxlz1Eu81PO6xKPhd/PYemzQQ0pP6Np6SNYy0L1zHxH8XdGQmhWCA
    3UTIdXNAy123kfhXoabNhBCqP6Q9Z1f2bcvl7YgDmAytwiIkZovfHWnKct6DS3ot
    mLzABR1BAgMBAAECggEBALLsiv5j5QbnOIphw5T3G0s3V5l30ev7+ux/sE7/Inj3
    j0uK+V1DZbAAeMqwpyW5Q5tH7aarGpb9iOYfgJG2YhrB8ZkKKV3XOp8MoapY4nJA
    cmXN1G87nzizzEC9bjg6JdL1F9sgjHLlCJps/4+2uMEVtDBt8tqxQPLWpzq+RGeM
    Udgu/l8uoNlhSStP5SNqGff7DDlnlzJXwi36jR0mIUYwaXLYuRDIzudg8v9Ktdry
    frNLv4gtjaWtx0WeOwsTiOFt/cSIQitxKM4a/qU21ZGbjllEIG2be5lyHBZ7jg6I
    OlYGBuFZ/eDU5O7lzx9Qbqj0sIduIxgkiCrNtqLUYZECgYEA9BmRTXhkIIozIArx
    XrQTjbjKwanvXIYtIfPPTf2yqaY3hRU+fj4EBGyWYBQErYcEkJUOCBsYD81lEt76
    Ng97m+xXVP8HdmYjX1FFUgXX0zXiRgqM4wJVf4vPVDsiuWjQNAzxSa5mpl+/PQ2B
    Nkj0ka+kgq9F6ZxoU/mcvZrwvCUCgYEAyspH+eVuZN6vvPxnvC1bWCYB61JzeV4j
    4Ds5zdaQMK+wmONtMOD4GO+Uy8OwWJPj7azMaM/jKTPMig9/VZuaQHvTBbz/au9Z
    Wpg480l5wsZP0jNLAiKgyJzRe1MQJkFNuMaAeipAQ7AI/tKKUsq+L9NSPr8ndUhj
    D7bPpP1gg+0CgYEAkpA/dFqTFA6mv9iSMKDDFNcdtsaIF+/gbYBsupFXkxFgSKIG
    0dn+o4FnkOy0GlT1YrJ8qFVMT0CuLXSAm7EUMPzpOvmdy3NsTbEIhEVJ32F9KTzw
    duVR3LFfnV2cbeMHEBmtTuZOcBsRQmE3cha/8jGZ/3Wp7qig47r+Z8H+RZkCgYAG
    YWLuW+ejSNZirdZdt1eeaGO7EbcMZIfgcDybW1riDUUTKmSvGwTzU+ZsmtWbk9ui
    CMPNsGzHSRfwaBhrix/JU5wKHC41IR7AmPWBwhgQpsiwJmj/wjMo3LZCmRRy/68A
    V06HiXjIKGvACMPNYw+k1ZNK4hzNtd9YCTpzSH2W6QKBgEK5T32RO48JPgNBE0/U
    bo2+sdrtub6BNHdADG02+JXgFIGTJB8/dQrtt6z5Gw59S+dV7bnQS7fE5MlA4uJ7
    FGFwXiOmvYw/KwEyRCVnDyx1YFYkBw1qaBHIJOoGXsH94BJMQZqzTkwWETFyYE1V
    75/RLvQ0Uz0jPJwOF0e12QdK
    -----END PRIVATE KEY-----

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: grpc-guide
    deployment: grpc-endpoint
  name: grpc-endpoint
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: server
    image: quay.io/redhatintegration/grpc-helloworld:1.0.0
    imagePullPolicy: Always
    env:
      - name: SSL_CERT_FILE
        value: "/certs/grpc-service.crt"
      - name: SSL_KEY_FILE
        value: "/certs/grpc-service.key"  
    ports:
    - name: grpc
      port: 9000
      containerPort: 9000
    volumeMounts:
      - name: config-volume
        mountPath: /certs
        readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: grpc-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-guide
    deployment: grpc-endpoint
  name: grpc-service
spec:
  selector:
    deployment: grpc-endpoint
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9000

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  labels:
    app: grpc-guide
  name: grpc-route
spec:
  to:
    kind: Service
    name: apicast-service
    weight: 100
  port:
    targetPort: proxy-tls
  tls:
    termination: passthrough
  wildcardPolicy: None